security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    superadmin:
                        password: 'superadminpw'
                        roles: ['ROLE_SUPER_ADMIN']
        fos_userbundle:
            id: fos_user.user_provider.username

    access_control:
        - { path: ^/user-api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user-api/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user-api/list, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user-api/edit, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/user-api/delete, role: ROLE_ADMIN }
        - { path: ^/api-doc, role: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_register:
            pattern:  ^/user-api/register
            stateless: true
            anonymous: true
        api_list:
           pattern:  ^/user-api/list
           stateless: true
           anonymous: true
        api_login:
            pattern:  ^/user-api/login
            stateless: true
            anonymous: true
            json_login:
                provider: chain_provider
                check_path:               /user-api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            provider: chain_provider
        api:
            pattern: ^/user-api
            stateless: true
            anonymous: false
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: admin_admin_index
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true