#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login:
  path: /user-api/login

app.swagger_ui:
  path: /api-doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }